### ISSUE TITLE
[BUG] Depending on the configuration, the memory should be precisely controlled

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1243]
### Describe the bug

The [deployment].cpu and [deployment].memory in the current configuration do not provide precise control over resources

**Comment by zipper-meng** [comment]
Do you like configuration format below?

```toml
[deployment]
cpu = 4
memory = '16G'
```
