### ISSUE TITLE
[BUG] Prometheus remote read cnosdb return warning: `remote_read: error reading response: snappy: corrupt input`

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1273]
### Describe the bug

Reading cnosdb data using Prometheus remote read  the  unexpected alert: `remote_read: error reading response: snappy: corrupt input`

But this doesn't affect the data I'm querying, and I'm not sure what effect this has on the returned results:

![image](https://github.com/cnosdb/cnosdb/assets/92921813/d301949b-a449-4f15-b40d-8904fa5f5bc9)

### To Reproduce

The software architecture is Grafana + Prometheus + CnosDB

The data crawled by Prometheus is written to CnosDB, and finally Prometheus is queried using Grafana.

1. Start the component with docker-compose

    ```shell
    docker-compose up -d
    ```

2. Create a database in cnosdb with the name `prometheus`

    ```sql
    create database prometheus
    ```
3. Use Grafana to query Promehteus after waiting more than an hour

### Additional context

This is the content of docker-compose:
```yml
version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.33.0
    container_name: prometheus
    restart: always
    user: root
    ports:
      - 9090:9090
    volumes:
          - ./etc/prometheus:/etc/prometheus
          - ./var/lib/prometheus:/var/lib/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/var/lib/prometheus'
      - '--storage.tsdb.retention.time=1h'
  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    restart: always
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./var/lib/grafana:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=123456
   cnosdb:
    image: cnosdb/cnosdb:community-latest
    container_name: cnosdb
    volumes:
      - ./etc/cnosdb:/etc/cnosdb
      - ./var/lib/cnosdb:/var/lib/cnosdb
      - ./var/log/cnosdb:/var/log/cnosdb
    ports:
      - "8901:8901"
      - "8902:8902"
      - "8903:8903"
      - "8904:8904"
      - "8905:8905"
    command:
      - /bin/bash
      - -c
      - |
          cnosdb run --config /etc/cnosdb/cnosdb.conf -M singleton
```

This is part of the Prometheus configuration:
```
scrape_configs:
  - job_name: "cnosdb"
    static_configs:
      - targets: ["cnosdb:8902"]

remote_write:
  - url: "http://cnosdb2:8902/api/v1/prom/write?db=prometheus"
    basic_auth:
      username: 'root'
      password: ''


remote_read:
  - url: "http://cnosdb2:8902/api/v1/prom/read?db=prometheus"
    read_recent: false
    basic_auth:
      username: 'root'
      password:
```
