### ISSUE TITLE
[Refactor] Some changes to config file

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/cnosdb#1689]
**Describe the issue**

Improve the config file, for issue **Only to start the configured service** #1685 

Config content in this comment is just a preliminary plan, not the final pattern of config. 

```toml
[global]
node_id = 1001
host = "localhost"
cluster_name = 'cluster_xxx'
meta_service_addr = ["127.0.0.1:8901"]
report_time_interval_secs = 30
cold_data_server = false
store_metrics = true

[deployment]
mode = 'query_tskv'
cpu = 8
memory = 16

[query]
max_server_connections = 10240
query_sql_limit = 16777216
write_sql_limit = 167772160
auth_enabled = false
read_timeout_ms = 3000
write_timeout_ms = 3000
stream_trigger_cpu = 1
stream_executor_cpu = 2

[storage]
path = '/var/lib/cnosdb/data'
max_summary_size = '128M'
base_file_size = '16M'
flush_req_channel_cap = 16
max_cached_readers = 32
max_level = 4
compact_trigger_file_num = 4
compact_trigger_cold_duration = '1h'
max_compact_size = '2G'
max_concurrent_compaction = 4
strict_write = false

[wal]
enabled = true
path = '/var/lib/cnosdb/wal'
wal_req_channel_cap = 64
max_file_size = '1G'
flush_trigger_total_file_size = '2G'
sync = false
sync_interval = '0'

[cache]
max_buffer_size = '128M'
max_immutable_number = 4
partition = 8

[log]
level = 'info'
path = '/var/log/cnosdb'

[security]
[security.tls_config]
certificate = "./config/tls/server.crt"
private_key = "./config/tls/server.key"

[service.http]
tcp_listen_port = 8902

[service.internal]
grpc_listen_port = 8903

[service.flight_rpc]
tcp_listen_port = 8904

[service.opentsdb]
tcp_listen_port = 8905

[service.vector]
tcp_listen_port = 8906

[service.report]
# enabled = true

[cluster]
raft_logs_to_keep = 5000
using_raft_replication = false

[hinted_off]
enable = true
path = '/var/lib/cnosdb/hh'
threads = 3

[heartbeat]
report_time_interval_secs = 30

[trace]
auto_generate_span = false
```
