### ISSUE TITLE
[BUG]Promtail failed to parse logs

### ISSUE THREAD

**Issue by Benxiaohai001** [cnosdb/cnosdb#2300]
### Describe the bug

Promtail failed to parse logs
version:cnosdb 2.4.2, revision c6a177786a823ff5b3cd991464e898fb7b413cad
deploy:sinleton

### To Reproduce

config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:8902/api/v1/es/_bulk?db=prometail&table=table4&log_type=loki
    basic_auth:
      username: root
      password:

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      stream: stdout
```

```
./promtail-darwin-arm64 --config.file=./promtail_local_config.yaml
```
