### ISSUE TITLE
[Configuration] Changes about config.toml

### ISSUE THREAD

**Issue by zipper-meng** [cnosdb/cnosdb#580]
**Describe the issue**
As the config items increases, config file seems to be more and more disordered. We should organize config items in a certain way.

**What you like us to do**

One of the ways is shown below:

```toml
[storage]
# Directory for summary: $path/summary/
# Directory for index: $path/index/$database/
# Directory for tsm: $path/$database/tsm/
# Directory for delta: $path/$database/delta/
path = 'dev/db'
max_summary_size = 134217728 # 128 * 1024 * 1024
max_level = 4
base_file_size = 16777216 # 16 * 1024 * 1024
compact_trigger = 4
max_compact_size = 2147483648 # 2 * 1024 * 1024 * 1024
dio_max_resident = 1024
dio_max_non_resident = 1024
dio_page_len_scale = 1

[wal]
enabled = true
path = 'dev/wal'
sync = true

[cache]
max_buffer_size = 1048576 # 134217728 # 128 * 1024 * 1024
max_immutable_number = 4
```

**Additional context**
Add any other context about the issue here.
