### ISSUE TITLE
[Feature] Support prometheus remote write

### ISSUE THREAD

**Issue by ZuoTiJia** [cnosdb/cnosdb#858]
We will support remote writing with Prometheus.

You need to add the following configuration in the prometheus.yml file to use this feature.

```yml
# remote_write cnosdb
remote_write:
  - url: "http://localhost:31001/api/v1/prom/write?db=prometheus"
    basic_auth:
      username: 'root'
      password: ''
```
Please confirm to **create** the corresponding **database** before using this featrue.
